"""add invoice sequence

Revision ID: 59c6283aeb7f
Revises: f8ee2909b4a1
Create Date: 2025-01-28 23:00:46.031532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59c6283aeb7f'
down_revision: Union[str, None] = 'f8ee2909b4a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 